# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-01 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20180901_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='has_confirmed',
            new_name='has_actived',
        ),
    ]
